### ISSUE TITLE
Issue uploading file with open-uri

### ISSUE THREAD

**Issue by hallmatt** [claudiob/yt#201]
Hello-

I'm getting an error with the "open" function on like 72 of Account.rb while trying to upload a video via a MP4 URL. 

Here's the full error I'm getting when uploading a video:

```
TypeError: no implicit conversion of Symbol into String
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/open_uri_redirections-0.1.1/lib/open-uri/redirections_patch.rb:33:in `delete'
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/open_uri_redirections-0.1.1/lib/open-uri/redirections_patch.rb:33:in `open_uri'
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/open-uri.rb:689:in `open'
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/2.0.0/open-uri.rb:34:in `open'
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/yt-0.24.7/lib/yt/models/account.rb:72:in `upload_video'
  from (irb):19
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in `start'
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'
  from /Users/user_account/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/railties-3.2.18/lib/rails/commands.rb:41:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

If I try and imitate the code by running:

```
open(mp4_url)
```

And then follow lines 73-77 of Account.rb (https://github.com/Fullscreen/yt/blob/61f5c8227c703a49fd5e928d5b9af01042cf713b/lib/yt/models/account.rb) the video uploads fine. So it looks like line 72 needs to have the 'rb' removed or passed in differently.

**Comment by stavro** [comment]
Hi @hallmatt .. From your error printout, it appears you are using a gem called `open_uri_redirections` which attempts to apply a patch to `open-uri`.

``` ruby
require 'open-uri' #=> true
open "http://google.com", "rb" #=> #<Tempfile:

require 'open_uri_redirections' #=> true
open "http://google.com", "rb" #=> TypeError: no implicit conversion of Symbol into String
```

Please upgrade `open_uri_redirections` to the lastest version (which will fix the error) or remove it completely.

If you still have issues afterwards, feel free to reopen the ticket.

**Comment by hallmatt** [comment]
That'll do it! Thanks!
